# AI Review Agents Configuration
# برای CodeRabbit و Gemini - فقط کامنت در PR

project:
  name: "Diabetes Pilot (Helssa continuation)"
  base_branch: "develop"
  
trigger:
  events: ["pull_request"]
  branches: ["feat/phase-*"]
  
mode: "comments_only"  # فقط کامنت، بدون تغییر فایل

# منابع مجاز برای هر دو agent
allowed_sources:
  - "/doc/phase1/should-*.md"
  - "/doc/phase2/should-*.md"
  - "/doc/phase3/should-*.md"
  - "/doc/phase4/should-*.md"
  - "/doc/phase5/should-*.md"
  - "/doc/phase6/should-*.md"
  - "/doc/phase7/should-*.md"
  - "/doc/phase8/should-*.md"
  - "/cursoragent/AGENT.MD"
  - "/cursoragent/CODING_RULES.md"

# قوانین مشترک
rules:
  - id: "only_should_files"
    description: "فقط مطابق should-* فایل‌ها بررسی شود"
    severity: "error"
  - id: "helssa_compatibility"  
    description: "سازگاری با Helssa الزامی است"
    severity: "critical"
  - id: "no_file_changes"
    description: "هیچ فایلی تغییر نکند، فقط کامنت"
    severity: "critical"
  - id: "phase_scope_only"
    description: "فقط فایل‌های فاز جاری بررسی شود"
    severity: "error"

# قالب‌های کامنت برای هر فاز
phase_templates:
  "phase-01-setup":
    focus: ["infrastructure", "dependencies", "Docker", "settings"]
    helssa_check: ["namespace compatibility", "environment setup"]
    
  "phase-02-models":
    focus: ["data models", "relationships", "migrations"]
    helssa_check: ["model compatibility", "field naming", "migration safety"]
    
  "phase-03-versioning":
    focus: ["append-only design", "revert mechanism", "performance"]
    helssa_check: ["versioning strategy", "data integrity"]
    
  "phase-04-api":
    focus: ["ViewSets", "JWT auth", "endpoints", "serializers"]
    helssa_check: ["API conventions", "authentication flow"]
    
  "phase-05-ai":
    focus: ["Celery tasks", "OpenAI integration", "error handling"]
    helssa_check: ["async processing", "external service integration"]
    
  "phase-06-references":
    focus: ["clinical references", "M2M relationships", "data seeding"]
    helssa_check: ["clinical workflow compatibility", "data standards"]
    
  "phase-07-security":
    focus: ["RBAC", "audit logs", "data export", "permissions"]
    helssa_check: ["security model", "compliance", "data protection"]
    
  "phase-08-testflow":
    focus: ["integration tests", "end-to-end flow", "test coverage"]
    helssa_check: ["test strategy", "production readiness"]

# کامنت استایل‌ها
comment_styles:
  coderabbit:
    summary_prefix: "## 📋 CodeRabbit Review"
    issue_prefix: "🤖 CodeRabbit:"
    reference_format: "مرجع: /doc/phaseX/should-*.md"
    
  gemini:
    summary_prefix: "## 🧠 Gemini High-Level Review"  
    issue_prefix: "🧠 Gemini:"
    reference_format: "تحلیل بر اساس: /doc/phaseX/should-*.md"

# ممنوعیت‌ها
forbidden_actions:
  - "file_creation"
  - "file_modification" 
  - "file_deletion"
  - "branch_creation"
  - "merge_actions"
  - "external_api_calls"