version: '3.9'
services:
  web:
    build: .
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  worker:
    build: .
    command: celery -A config.celery_app worker -l info
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - db
  beat:
    build: .
    command: celery -A config.celery_app beat -l info
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: diabetes
      POSTGRES_USER: diabetes
      POSTGRES_PASSWORD: diabetes
    ports:
      - "5432:5432"