version: '3.9'

services:
  web:
    build: .
    env_file: .env
    environment:
      - USE_SQLITE=${USE_SQLITE:-True}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-True}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1}
    command: sh -c "python manage.py migrate && uvicorn config.asgi:application --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
