version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-diabetes}
      - POSTGRES_USER=${POSTGRES_USER:-diabetes}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-diabetes}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-diabetes} -d ${POSTGRES_DB:-diabetes}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    command: sh -c "python manage.py migrate && uvicorn config.asgi:application --host 0.0.0.0 --port 8000"
    env_file: .env
    environment:
      - USE_SQLITE=${USE_SQLITE:-False}
      - POSTGRES_DB=${POSTGRES_DB:-diabetes}
      - POSTGRES_USER=${POSTGRES_USER:-diabetes}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-diabetes}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
