version: '3.9'
services:
  web:
    build: .
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
  worker:
    build: .
    command: celery -A config.celery_app worker -l info
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
  beat:
    build: .
    command: celery -A config.celery_app beat -l info
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: diabetes
      POSTGRES_USER: diabetes
      POSTGRES_PASSWORD: diabetes
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    ports:
      - "9000:9000"
      - "9001:9001"
