blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/your-username/gitDM/blob/main/README.md
    about: Check the documentation for setup and usage instructions
  - name: 💬 Discussions
    url: https://github.com/your-username/gitDM/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/your-username/gitDM/security/advisories/new
    about: Report security vulnerabilities privately
